### ISSUE TITLE
EOF exception

### ISSUE THREAD

**Issue by MatteCarra** [Steveice10/OpenNBT#4]
MCProtocolLib version 1.7.7
Connecting to mc.parkercraft.it (1.7 -> 1.8 server)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
	at org.spacehq.opennbt.NBTIO.readTag(NBTIO.java:141)
	at org.spacehq.mc.protocol.util.NetUtil.readNBT(NetUtil.java:32)
	at org.spacehq.mc.protocol.util.NetUtil.readItem(NetUtil.java:67)
	at org.spacehq.mc.protocol.packet.ingame.server.window.ServerWindowItemsPacket.read(ServerWindowItemsPacket.java:38)
	at org.spacehq.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:41)
	at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:316)
	... 29 more

**Comment by Steveice10** [comment]
Are you connecting to a server with the right protocol version? ("1.7 -> 1.8 server"?) Sounds like either an issue with the server sending bad data or the protocol library reading something wrong.

**Comment by MatteCarra** [comment]
Yes in the handshake packet I am sending the right protocol number

**Comment by MatteCarra** [comment]
Uhm perhaps I understand the problem.
I will check and update you.
Thank you!

**Comment by Steveice10** [comment]
The game version of the MCProtocolLib build you are using must match up with the game version of the server you are connecting to.
